Develop
R4Ajeti/Advanced_Building_Blocks pull request #1
Opened 2019-08-22 23:58 UTC by R4Ajeti

2019-08-23 08:24 UTC, bolah2009 requested changes
## Awesome Job :muscle: 

#### I tested all method only two seems to be inefficient. :smile: Nice. :wink: 

- See comments for required changes.
- Keep your code clean, please fix this. Currently `rubocop` reported **190 offenses**. :open_mouth:
You can fix this by running `rubocop -a` in the project root directory assuming you have `rubocop gem` installed.   
  > Keep your code [clean](https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#ruby-style-guide).

Do this and submit for another code review request.

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-08-23 08:24 UTC, bolah2009 commented on Enumerable.rb
> +    def my_none?
#### `REQUIRED`

#### '#my_none?` should be able to take an argument.

> If instead a pattern is supplied, the method returns whether pattern === element for none of the collection members.

##### Learn more [here](https://ruby-doc.org/core-2.6.3/Enumerable.html#method-i-none-3F).

```ruby
$ irb
irb(main):001:0> require_relative './Enumerable'
=> true
irb(main):002:0> [1,2,3,4,5].none?(3)
=> false
irb(main):003:0> [1,2,3,4,5].none?(9)
=> true
irb(main):004:0> [1,2,3,4,5].my_none?(9)
Traceback (most recent call last):
        5: from /home/bola/.rbenv/versions/2.6.3/bin/irb:23:in `<main>'
        4: from /home/bola/.rbenv/versions/2.6.3/bin/irb:23:in `load'
        3: from /home/bola/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):4
        1: from /media/bola/.../code-reviews/Advanced_Building_Blocks/Enumerable.rb:41:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
irb(main):005:0> 
```

2019-08-24 10:06 UTC, bolah2009 requested changes
## Hi @R4Ajeti 

The two methods **(`my_count` and `my_none`)** are still not working as expected as shown above., test the methods with the ruby methods. Visit the link attached in the previous comments to learn more about the behavior of these methods.

:bulb: Test the same method with different parameter types (eg block, numbers)

Do this and submit for another code review request.

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-24 10:06 UTC, bolah2009 commented on Enumerable.rb
> +  def my_count?
:thinking: Is this the same with `def my_count(*args)` ?

2019-08-28 01:19 UTC, jofer86 requested changes
# :clap: :clap: Great Effort!!!!
Just a couple of minor fixes required on your code before you are able to move forward, please look at my comments below and DDT those bugs!!!.

Cheers, Jorge.

2019-08-28 23:38 UTC, maelfosso requested changes
Hello,

Really nice improvement.
But there is **just one bug to fix**
Check the comment below.

Kindly make the changes and re-submit a new code review request.
A thumb-up is waiting for you :-)

2019-08-28 23:38 UTC, maelfosso commented on Enumerable.rb
> +  def my_count(*args)
# There is a new bug

Take a look below
```ruby
irb(main):004:0> [1,2,3,4,5,6,7,8].my_count
=> 8
irb(main):005:0> [1,2,3,4,5,6,7,8].count
=> 8
irb(main):006:0> [1,2,3,4,5,6,7,8].count(2)
=> 1
irb(main):007:0> [1,2,3,4,5,6,7,8].my_count(2)
=> 1
irb(main):008:0> [1,2,3,4,5,6,7,8].count { |x| x.even? }
=> 4
irb(main):009:0> [1,2,3,4,5,6,7,8].my_count { |x| x.even? }
=> 8
```

2019-09-02 16:19 UTC, bolah2009 approved these changes
# Nice Job @R4Ajeti 

### Good Job implementing all suggested changes. It's a :+1: from me...

Use apprortaite `.rubocop.yml` file as shown in the comment below before merging, currently `rubucop` detected `64 offenses`. Kindly fix this too. :ok_hand: 

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-09-02 16:19 UTC, bolah2009 commented on .rubocop.yml
> +  ExcludedMethods: ['describe']
### Please use the approprate [`.rubocop.yml` file](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml).
```yml
AllCops:
  Exclude:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20
Metrics/AbcSize:
  Include: ["app/controllers/*"]
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
```

2019-09-02 17:23 UTC, merged